### PR TITLE
Modified conditions for snowball head code

### PR DESCRIPTION
**Pull request by noelforte**
Added check for home and front pages so custom head code is not injected there, in the event that the most recently published post was of the snowball type.

### CODE REVIEW

**Comment by thomaspark** [comment]
Nice catch. However, someone might set the front page to a single post and would want the custom head code in that case. You could handle this by reusing the condition from the `snowball_template` function:

```
  $postid = get_the_id();

  if ((get_post_type($postid) == 'snowball') && (is_single($postid) || get_option('page_on_front') == $postid)) {
```

I'll merge the eventual fix and add it to the next release. Thanks.

**Comment by noelforte** [comment]
Awesome. I'll try that.

**Comment by thomaspark** [comment]
@noelforte, did you want to submit another pull request for this? Happy to merge yours, or add it myself.

**Comment by noelforte** [comment]
You can go ahead and add it.

**Pull request closed without merging**
