### PR TITLE
add darken splash background functionality, closes #183

### LINKED ISSUE #183: Darken splash background (Increase decrease contrast)

### PR DESCRIPTION
**Pull request by sukritchhabra**
* Adding a slider to splash module that allows darkening of background.
* Also changing gulp-uglify version to 1.5.4 in package.json.

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @sukritchhabra, this looks and works great! What if we changed the max opacity from 0.5 to 1.0 to give it the full range?

**Comment by sukritchhabra** [comment]
I had refrained earlier from giving it a 1.0 because the overlay becomes completely black. But I just added that :)

**Comment by thomaspark** [comment]
Yeah, there might be some confusion if someone goes to 100%, but there might be a need for all the way up to 99%.

Looks good, just one more thing. Now that opacity goes to 1.0, we probably also want the step value to change from 0.005 to 0.01.

**Comment by sukritchhabra** [comment]
Yup that makes sense. Just made that change :)

**Pull request merged**
