### PR TITLE
Adding radio buttons for width options (text block), resolves #181

### LINKED ISSUE #181: Text blocks need some padding on the left and right side.
- The text sticks to the edges of the page and needs some padding.

### PR DESCRIPTION
**Pull request by sukritchhabra**
- Adding Radio buttons as width options
- The 3 options now are `Full Width`, `Fluid` and `Fixed`
- Was unsure how to scope them or whether to make them global, therefore scoping them to `.snowbal-block-text`. (_We can change this if needed_)

### CODE REVIEW

**Comment by sukritchhabra** [comment]
@thomaspark I just realized this hadn't been merged. Could you take a look at this and let me know if something needs to be changed? Thanks :)

**Comment by thomaspark** [comment]
Hey @sukritchhabra, this looks good (still have to test) but can you exclude the changes to all the min files in the pull request?

**Comment by sukritchhabra** [comment]
Hey @thomaspark, gotcha! Just removed all the minified files.

**Comment by thomaspark** [comment]
I tested it out and it's looking good. Could you make a few tweaks?
- Rename from "Full Width" to "Full" to be consistent with the other values.
- Reorder as Fixed > Fluid > Full, with Fixed as the default.
- The `.snowball-block-text.fixed-width` style can be removed, since the default style of blocks is already a fixed 600px.
- Move `.fluid-width` style to `snowball.css`/ `snowball.min.css`. Makes sense to put it alongside `.full-width` and `.mid-width`, and this also allows the full width media queries to kick in for mobile.

Let me know if you have any questions or thoughts about these suggestions. Thanks!

**Comment by sukritchhabra** [comment]
Hey @thomaspark, just made the changes you mentioned. Let me know if you think something else needs to be changed :)

**Comment by thomaspark** [comment]
Perfect, thanks Sukrit! This feature will be included in the next release.

**Comment by sukritchhabra** [comment]
Awesome :)

**Comment by sukritchhabra** [comment]
Awesome :)

**Pull request merged**
